### ISSUE TITLE
Build Travis en échec à cause des tests

### ISSUE THREAD

**Issue by Bludwarf** [Bludwarf/cuetube#142]
https://travis-ci.org/Bludwarf/cuetube/jobs/372377471#L1882

```
Uncaught Error: Cannot find module "."
at http://localhost:9876/_karma_webpack_/main.bundle.js:801:2212

Error: Cannot find module "."
    at webpackMissingModule (http://localhost:9876/_karma_webpack_/main.bundle.js:801:2144)
    at e (http://localhost:9876/_karma_webpack_/main.bundle.js:801:2222)
    at http://localhost:9876/_karma_webpack_/main.bundle.js:801:2344
    at http://localhost:9876/_karma_webpack_/main.bundle.js:798:34494
    at Object.<anonymous> (http://localhost:9876/_karma_webpack_/main.bundle.js:801:635)
    at Object../src/scripts/CueParser.js (http://localhost:9876/_karma_webpack_/main.bundle.js:802:30)
    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)
    at Object../src/CueService.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:339:23381)
    at __webpack_require__ (http://localhost:9876/_karma_webpack_/inline.bundle.js:55:30)
    at Object../src/app/player/player.component.ts (http://localhost:9876/_karma_webpack_/main.bundle.js:663:246844)
```

**Comment by Bludwarf** [comment]
Les TU passent, il reste maintenant les Tests de bout-en-bout (E2E).
Pistes : 

- https://github.com/angular/protractor/issues/4850
- https://github.com/angular/angular-cli/issues/2176
- https://intoli.com/blog/installing-google-chrome-on-centos/

**Comment by Bludwarf** [comment]
Corrigé en suivant :

- https://github.com/angular/protractor/issues/4857
- https://kendaleiv.com/a-complete-protractor-travis-ci-solution-for-angular-e2e-testing/
